{{- if .Values.backupsEnabled }}
{{- range $i, $location := (.Values.configuration.backupStorageLocation) }}
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  {{ if .name -}}
  name: {{ .name }}
  {{- else -}}
  name: {{ include "velero.backupStorageLocation.name" . }}-{{ $i }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade,post-rollback
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $ }}
spec:
  credential: 
    name: {{ .credential.name }}
    key: {{ .credential.key }}
  provider: {{ .provider }}
  {{ if .accessMode -}}
  accessMode: {{ .accessMode }}
  {{- else -}}
  accessMode: ReadWrite
  {{- end }}
  {{- with .default }}
  default: {{ . }}
  {{- end }}
  objectStorage:
    bucket: {{ .bucket | quote }}
    {{- with .prefix }}
    prefix: {{ . | quote }}
    {{- end }}
    {{- with .caCert }}
    caCert: {{ . }}
    {{- end }}
{{- with .config }}
  config:
{{- range $key, $value := . }}
{{- $key | nindent 4 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
